### ISSUE TITLE
能写个readme把你的地址贴出来吗kao

### ISSUE THREAD

**Issue by FutaoSmile** [lsc95/lsc95.github.io#1]
能写个readme把你的地址贴出来吗kao

**Comment by lsc95** [comment]
you can visit http://lsc95.github.io. Your comment is impolite, if you have some question you can send me a n email to coderli95@163.com.

**Comment by FutaoSmile** [comment]
Google翻译用的可以的呀春春

**Comment by lsc95** [comment]
This issues is closed, if you have some question you can open a new issues.
